//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagerSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCong
    {
        public int Ca { get; set; }
        public int MaNV { get; set; }
        public int MaSoBan { get; set; }
    
        public virtual BanAn BanAn { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
