//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagerSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gia
    {
        public System.DateTime NgayADGia { get; set; }
        public int MaThucDon { get; set; }
        public Nullable<double> Gia1 { get; set; }
    
        public virtual ThucDon ThucDon { get; set; }
    }
}
